name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'

    - name: Flutter Clean
      run: flutter clean

    - name: upgrade
      run: flutter upgrade --force

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Flutter Pub Upgrade
      run: flutter pub upgrade

    - name: Flutter Build APK
      run: |
        flutter build apk
        ls -ll
